# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd7b5039a74222c3eba499d5d24ed2378ff4f167e84ecd8cfebeed681493d0870bee331cfabb8833789850b6782d43fe476ca7391f576beeada970dbde94171

test:
  secret_key_base: 17abc860c02d31b6643ce5cc7824ffb0bccfa5b255025ebb68331b485c62e3239c92e4d3d1b70743271dbe2fd4aebbd26ecc0797b54708fc6da0ea0332d2ce15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
