# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fecde8c8abb8d1f1034d17fceb37460400e23db0b9ba624dfc42f57d9e33fcdb51256b2f5d96bd48fa39de04f86abc0459ff48a3fe94721286be0c794248276

test:
  secret_key_base: 80d600047272e15836d1236e25aa86bc50bf791e17557f29928c5d2dc437eacce6be6fd8ff0ed58c3d4e38fecae2ac34a212b85842740987faa65773a956c89f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
